### ISSUE TITLE
Napalm routerOS 

### ISSUE THREAD

**Issue by zleppy** [netboxlabs/orb-agent#37] opened 2024-12-20 21:08 UTC
When trying to ingest a routeros device with napalm-ros driver added into orb. i keep getting this error in the logs

{"level":"info","ts":"2024-12-20T20:54:01.639Z","caller":"devicediscovery/device_discovery.go:148","msg":"device-discovery stderr","log":"ERROR:device_discovery.policy.runner:Policy discovery_1, Hostname 192.168.0.1: module 'librouteros' has no attribute 'DEFAULTS'"}

ive tested the config and it works with a IOS device.

**Comment by rboucher-me** [comment] 2024-12-20 21:36
Can you share your `drivers.txt` and agent config file (with any sensitive information removed) so that we can try to reproduce the issue? thanks

**Comment by leoparente** [comment] 2024-12-20 22:32
Hi @zleppy thanks for the feedback. I've done some investigation and the issue seems to be in the [napalm-ros](https://github.com/napalm-automation-community/napalm-ros) driver itself:

napalm-ros requires [librouteros](https://github.com/luqasz/librouteros) >= 3.2.0. So when you install the driver, the actual version that is being installed is 3.4.0. However, there was a breaking change when they renamed a variable in 3.4.0 release.

that said, I think one solution that you could try for now is to specify the version librouteros in your driver.txt as well like

````
librouteros==3.2.0
napalm-ros
````

I will open a bug on napalm-ros now reporting this issue

**Comment by zleppy** [comment] 2024-12-21 00:43
librouteros==3.2.0
This works! 

Seeing another strange issue is that the interfaces are reported with negative speed value. 
i dont think this is a issue with diode/orb, but a bug in napalm-ros? 

            "name": "VLAN_0001",
            "enabled": true,
            "mtu": 1500,
            "macAddress": "",
            "speed": -1000,
            "description": ""

made a tiny script to work around the issue. 

sed -i "s/'speed': -1.0/'speed': 1.0/" /usr/local/lib/python3.12/site-packages/napalm_ros/ros.py

this works when i was playing around with the "Diode NAPALM agent"

**Comment by leoparente** [comment] 2024-12-23 13:18
great. They also updated librouteros after I've reported the break compatibility issue: https://pypi.org/project/librouteros/3.4.1/#history so if you install latest, it will be v3.4.1. I will close this ticket

**Closed as completed by leoparente** 2024-12-23 13:18 UTC
